Update pineline.yml

diff --git a/.github/workflows/pineline.yml b/.github/workflows/pineline.yml
--- a/.github/workflows/pineline.yml
+++ b/.github/workflows/pineline.yml
@@ -9,7 +9,7 @@ on:
     branches: [ "main" ]
 
 jobs:
-  build:
+  build-test:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -23,8 +23,29 @@ jobs:
         cache: 'yarn'
     - name: Install package for node_modules
       run: yarn
+      
     - name: Running test coverage
       run: yarn test:coverage
+      
+    - name: Check coverage percentage
+      run: |
+        COVERAGE=$(grep -oP "Statements\s*:\s*\K[0-9]+" coverage/coverage-summary.json)
+        if [ "$COVERAGE" -lt 85 ]; then
+          echo "Error: Coverage is less than 85%"
+          exit 1
+        fi
+        
+  upload-coverage:
+    needs: build-test
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: Upload coverage to Codecov
+      uses: codecov/codecov-action@v1
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
     # - name: Upload coverage to Codecov
     #   uses: codecov/codecov-action@v1
     #   with:
